/* THE BIBEL, chapters five to eight. */
export const PART_ONE_B = [
  { id: 'v', no: 'V', title: 'THE LAW, IN ITS PARTS', verses: [
    'And on the mountain the Law was given. And it was given in ten parts; and in six hundred and thirteen parts; and in eight parts arranged as a path; and in five parts, of which the second is the difficult one. And the people asked which was meant, and it was answered that it was the same Law, counted by different hands, and that the hands had all been correct.',
    'Honour thy father and thy mother. Thou shalt not kill. Thou shalt not steal. Thou shalt not covet thy neighbour\'s house, nor his wife, nor his manservant, nor his maidservant, nor his ox, nor his ass, nor anything that is thy neighbour\'s; nor his opinions about the ox, which are many, and which he holds firmly, and which are his.',
    'Right view, right intention, right speech, right action, right livelihood, right effort, right mindfulness, right concentration: these eight are the path, and the path is walked, and it is not walked quickly, and it is not left. And the one who walks it is not asked to hurry, but only to continue, and to be right.',
    'Say there is no god but God. Pray, five times in the day, turning to the one house; and the one house is in the one place, and every person turns to it from wherever they stand, and it is therefore at the centre of every person at once. Fast in the month appointed. Journey once, if thou art able. And of what thou hast, give one part in forty, and do not announce the amount.',
    'Be kind before thou art right. Be right before thou art loud. Wash thy hands, and thy feet, and thy face, and the washing shall be thorough, and shall not be done twice in a hurry. Eat what is clean. Leave the corner of the field. Let the land lie fallow in the seventh year, and let it be known to the land.',
    'Rest one day in seven; and if thou hast forgotten which day it is, rest anyway, and argue later; for the people have kept the seventh day, and the sixth, and the first, in their order, and have been rested in all three cases, and it has not been found that God was displeased by the number.',
    'And Moses came down from the mountain with the two tables of testimony in his hand; and the tables were written on both their sides; on the one side and on the other were they written. And they were weighed, and the weight of the tables was the weight of what was written on them, and it is the same weight to this day, and is carried, and is not too heavy.'
  ] },
  { id: 'vi', no: 'VI', title: 'THE WHEEL AND THE LEDGER', verses: [
    'And it is written that the soul returns; that it ascends or descends according to its deeds; that it comes again in the body of a king, or of a worm, or of a bird that does not know it was once a king. And the wheel turns, and has turned beyond number, and each turn is a life, and the lives are counted in the ledger of the one who keeps it.',
    'And it is also written that the soul does not return, and is weighed once, at the gate, against a feather; and the heart is placed upon the one scale, and the feather of truth upon the other; and the beast that waits beneath the scale does not eat the light heart, and the light heart goes on. And that is the end of the matter, and the matter is closed.',
    'And it is further written that the soul rests until a trumpet sounds; that it lies as in a sleep in the dust of the earth, or in the presence, or under the stone; and that on the day of the trumpet the dead shall rise, every one in his order, and the books shall be opened, and a man shall be given his book in his right hand, and shall read it, and shall know it for his.',
    'And the scribes were brought together, and were asked to reconcile the three accounts, the returning and the weighing and the sleeping. And the scribes said that the matter was weighty, and that they required time. And time was given them. And at the end of the time the scribes asked for more time, and it was given, and the scribes are working.',
    'And in the interim it is recommended that thou behave as though all three accounts were true; for this produces very nearly the same conduct as believing none of them, but with better posture.',
    'And the elders have noted that the three accounts agree on one thing, which is that there is a keeper of the ledger, whatever the ledger is, and whoever the keeper is; and that the keeper is patient; and that what is written is not erased; and that the one who comes in good faith is not asked to understand the ledger, but only to have been honest in his entries.'
  ] },
  { id: 'vii', no: 'VII', title: 'THE PROPHETS, AND THEIR RECEPTION', verses: [
    'And prophets were sent to every people; and every people said unto them, Not now; we are eating. And the prophets waited; and the people finished their meal, and began another; and the prophets are waiting still in certain cities, outside certain doors, in the weather, with their message, which is short.',
    'And one was swallowed by a great fish, and was in the belly of the fish three days and three nights, and prayed; and the fish vomited him out upon the dry land, and he went to Nineveh, and said what he had been sent to say; and the city repented, from the king to the cattle, who were put in sackcloth, and Jonah was displeased, because he had been correct and nothing had come of it.',
    'And one sat under a tree until he understood everything; and having understood everything, he rose, and went to explain it to people who had not sat under the tree. And they asked him what it was he understood, and he told them, and it took forty-five years, and they understood most of it, and the tree is still there, in a manner.',
    'And one was born in a stable, because there was no room at the inn; and the innkeeper has never forgotten it, and has never been allowed to; and he is mentioned in every account of the night, and is not named, and has been dead two thousand years, and did what he could, and had a full house.',
    'And one received the recitation in a cave, on a mountain, in the night; and the angel said, Read; and he said, I cannot read; and the angel pressed him until the breath went out of him, and said, Read; and he was, quite reasonably, terrified, and ran down the mountain, and said to his wife, Cover me; and she covered him; and she believed him first.',
    'And not one of them enjoyed it. And this is the surest evidence that they were not making it up. For a man who invents a message gives himself a pleasant one, and is received at the door, and is fed; and a man who is given a message gives it, because it was given, and goes where he is not welcome, and says it anyhow, and goes home.',
    'And the compilers have gone through the testimonies, and have found that each of the prophets was refused at least once, and fed at least once, and that on the whole the feeding was the harder to bear.'
  ] },
  { id: 'viii', no: 'VIII', title: 'ON THE END OF THINGS', verses: [
    'There will be a last day. And there will be a battle, upon a plain; the place of it is named in some accounts Megiddo and in others Vigrid, and its dimensions are given as a hundred leagues on each side, and the dimensions of the two are the same, and it is the same plain.',
    'And there will be a bridge, finer than a hair and sharper than a sword, over which all must pass; and the righteous shall cross it in the blink of an eye, and the rest shall cross it by degrees, and the bridge is called Sirat in the one country and Chinvat in the other, and it is the same bridge, and the people who cross it are the same people, one after another.',
    'And there will be a serpent that eats the world, having its tail in its mouth, and the world within the ring of the serpent; and the serpent will let go; and there will be a dance, which is the dance that ends the world, and the one who dances it dances it as it must be danced, in every step, to the end, with four arms.',
    'And after the dance there will be a long quiet afternoon, in which nothing happens at all. And it is written that this afternoon is the longest of the days, and that the light of it is even, and that the air is neither warm nor cool; and that those who are in it do not ask for anything to happen, but are content to be, and it is the reward.',
    'And the signs of the end are these: the sun shall rise in the west; the mountains shall walk; the seas shall boil; the rivers shall run backward to their source; and people shall be unkind to one another in new and inventive formats.',
    'Two of these signs have been reported continuously for four thousand years. And the scholars of every faith advise against booking anything.',
    'And a certain elder was asked how a man should live in the light of the end; and he answered that he should plant a tree. And he was asked, What if the end is tomorrow? And he answered, Plant it tomorrow, and plant it well, and water it; and the tree will be there, in whatever the afternoon is like, when it comes.'
  ] }
];
