/* THE BIBEL, part two, the first six accounts: the most extraordinary story of a people, told once, in full, and believed. Each is told from the people's own record and the compilers have added
   nothing to it but the order. */
export const PART_TWO_A = [
  { id: 'ix', no: 'IX', title: 'THE BOOK OF THE DONKEY', note: 'THE PEOPLE OF ISRAEL: NUMBERS, CHAPTER TWENTY-TWO', verses: [
    'Now Balak the son of Zippor, king of Moab, saw all that Israel had done to the Amorites; and Moab was sore afraid of the people, because they were many. And he sent messengers unto Balaam the son of Beor, a diviner of Pethor, which is by the river, saying: Behold, there is a people come out from Egypt; come now therefore, I pray thee, curse me this people.',
    'And God came unto Balaam, and said, Thou shalt not go with them; thou shalt not curse the people: for they are blessed. And Balaam rose up in the morning, and said unto the princes of Balak, Get you into your land: for the Lord refuseth to give me leave to go with you. And the princes sent again, more, and more honourable than they, and Balaam said that he could not go beyond the word of the Lord; and in the night God said, If the men come to call thee, rise up, and go with them.',
    'And Balaam rose up in the morning, and saddled his ass, and went with the princes of Moab. And God\'s anger was kindled because he went: and the angel of the Lord stood in the way for an adversary against him. Now he was riding upon his ass, and his two servants were with him. And the ass saw the angel of the Lord standing in the way, and his sword drawn in his hand: and the ass turned aside out of the way, and went into the field.',
    'And Balaam smote the ass, to turn her into the way. But the angel of the Lord stood in a path of the vineyards, a wall being on this side, and a wall on that side. And when the ass saw the angel of the Lord, she thrust herself unto the wall, and crushed Balaam\'s foot against the wall: and he smote her again. And the angel of the Lord went further, and stood in a narrow place, where was no way to turn either to the right hand or to the left. And when the ass saw the angel of the Lord, she fell down under Balaam: and Balaam\'s anger was kindled, and he smote the ass with a staff.',
    'And the Lord opened the mouth of the ass, and she said unto Balaam, What have I done unto thee, that thou hast smitten me these three times? And Balaam said unto the ass, Because thou hast mocked me: I would there were a sword in mine hand, for now would I kill thee. And Balaam was not astonished. It is not recorded that he was astonished. He answered her as one answers a colleague who has raised a point at the wrong moment.',
    'And the ass said unto Balaam, Am not I thine ass, upon which thou hast ridden ever since I was thine unto this day? was I ever wont to do so unto thee? And he said, Nay. And the compilers have weighed this reply, and have found it the most honest thing said in the whole matter, and have set it in the record by itself.',
    'Then the Lord opened the eyes of Balaam, and he saw the angel of the Lord standing in the way, and his sword drawn in his hand: and he bowed down his head, and fell flat on his face. And the angel said, Wherefore hast thou smitten thine ass these three times? Behold, I went out to withstand thee, because thy way is perverse before me: and the ass saw me, and turned from me these three times: unless she had turned from me, surely now also I had slain thee, and saved her alive.',
    'And Balaam said unto the angel of the Lord, I have sinned. And he went on, and from the high places he looked upon the camp, and where he had been sent to curse he blessed, three times, and a fourth; and this is the account. And the ass is not named in it, and is the one by whom the account was made possible, and her foot was not the one that was crushed.'
  ] },
  { id: 'x', no: 'X', title: 'THE BOOK OF THE SWINE', note: 'THE GOSPEL ACCORDING TO MARK, CHAPTER FIVE', verses: [
    'And they came over unto the other side of the sea, into the country of the Gadarenes. And when he was come out of the ship, immediately there met him out of the tombs a man with an unclean spirit, who had his dwelling among the tombs; and no man could bind him, no, not with chains: because that he had been often bound with fetters and chains, and the chains had been plucked asunder by him, and the fetters broken in pieces: neither could any man tame him.',
    'And always, night and day, he was in the mountains, and in the tombs, crying, and cutting himself with stones. But when he saw Jesus afar off, he ran and worshipped him, and cried with a loud voice, and said, What have I to do with thee, Jesus, thou Son of the most high God? I adjure thee by God, that thou torment me not. For he said unto him, Come out of the man, thou unclean spirit.',
    'And he asked him, What is thy name? And he answered, saying, My name is Legion: for we are many. And he besought him much that he would not send them away out of the country. And the number of the spirits was not given; and it was given afterward by those who counted what became of them, and the compilers have taken the number from them.',
    'Now there was there nigh unto the mountains a great herd of swine feeding. And all the devils besought him, saying, Send us into the swine, that we may enter into them. And forthwith Jesus gave them leave. And the unclean spirits went out, and entered into the swine: and the herd ran violently down a steep place into the sea, (they were about two thousand;) and were choked in the sea.',
    'And they that fed the swine fled, and told it in the city, and in the country. And they went out to see what it was that was done. And the herdsmen had counted the swine in the morning, and the number was two thousand, and they counted them again when they came down, and the number was none, and they went and wrote it so, in a ledger, and the ledger is not preserved, and the sum is.',
    'And they come to Jesus, and see him that was possessed with the devil, and had the legion, sitting, and clothed, and in his right mind: and they were afraid. And they that saw it told them how it befell to him that was possessed with the devil, and also concerning the swine. And they began to pray him to depart out of their coasts.',
    'And when he was come into the ship, he that had been possessed with the devil prayed him that he might be with him. Howbeit Jesus suffered him not, but saith unto him, Go home to thy friends, and tell them how great things the Lord hath done for thee, and hath had compassion on thee. And he departed, and began to publish in Decapolis how great things Jesus had done for him: and all men did marvel.',
    'And it is asked, in every generation, what was the worth of the swine against the worth of the man; and it is answered, by those who have kept the account, that the man was worth more than two thousand; and that this was not argued by anyone who was there, save the owners, who are not recorded as having been unreasonable, and who were afraid, and asked him to go, and he went.'
  ] },
  { id: 'xi', no: 'XI', title: 'THE BOOK OF THE HOOPOE', note: 'THE RECITATION: THE ANTS, VERSES SEVENTEEN TO FORTY-FOUR', verses: [
    'And there were gathered unto Sulayman his hosts, of the jinn and of men and of the birds, and they were set in rows. Until, when they came upon the valley of the ants, an ant said, O ants, enter your dwellings, lest Sulayman and his soldiers crush you while they perceive not. So he smiled, laughing at her speech, and said, My Lord, enable me to be grateful for Your favour which You have bestowed upon me.',
    'And he took attendance of the birds, and said, Why do I not see the hoopoe? Or is he among the absent? I will surely punish him with a severe punishment, or I will slaughter him, unless he brings me clear authorisation. And the roll was called of every bird, and he was not there, and the king waited, being a king who had heard an ant.',
    'But the hoopoe stayed not long, and said, I have encompassed that which you have not encompassed, and I have come to you from Sheba with certain news. Indeed, I found a woman ruling them, and she has been given of all things, and she has a great throne. I found her and her people prostrating to the sun instead of God, and Satan has made their deeds appear fair to them.',
    'He said, We will see whether you were truthful or were of the liars. Take this letter of mine and deliver it to them. Then leave them and see what they will return. And the hoopoe took the letter in his beak, and flew; and this is how the first postal service of the world was founded, and the bird was not paid, and did not ask.',
    'She said, O eminent ones, indeed, to me has been delivered a noble letter. Indeed, it is from Sulayman, and indeed it reads: In the name of God, the Entirely Merciful, the Especially Merciful. Be not haughty with me, but come to me in submission. And she consulted her council, and said, I am not deciding a matter until you witness for me. And she sent a gift; and Sulayman said, Will you provide me with wealth? What God has given me is better than what He has given you.',
    'He said, O assembly, which of you will bring me her throne before they come to me in submission? A powerful one from among the jinn said, I will bring it to you before you rise from your place; and indeed, I am for this strong and trustworthy. Said one who had knowledge of the Scripture, I will bring it to you before your glance returns to you. And when he saw it placed before him, he said, This is from the favour of my Lord, to test me whether I will be grateful or ungrateful.',
    'He said, Disguise for her her throne; we will see whether she will be guided or will be among those not guided. So when she arrived, it was said, Is your throne like this? She said, It is as though it were it. And she was invited to enter the palace; and when she saw it, she thought it was a body of water, and she uncovered her shins. He said, Indeed, it is a palace made smooth with glass. She said, My Lord, indeed I have wronged myself, and I submit with Sulayman to God, Lord of the worlds.',
    'And the compilers record that the hoopoe was not punished; that he was not slaughtered; that the clear authorisation was brought; and that the king who had listened to an ant, and had paused his army for it, listened also to a bird, who was late, and had been to Sheba, and was right.'
  ] },
  { id: 'xii', no: 'XII', title: 'THE BOOK OF THE ELEPHANT\'S HEAD', note: 'THE PEOPLES OF INDIA: THE PURANAS', verses: [
    'And it is written that Parvati, the consort of Shiva, was bathing on the mountain, and that Nandi, who kept her door, let in her husband without being asked, as he had always done; and Parvati was displeased, for she had been unattended, and there was no one in the world who was hers alone.',
    'And Parvati took the paste of turmeric which was upon her body, and the oil and the sandalwood and the scrapings, and she shaped of it a boy; and she breathed life into him; and he stood, and was her son, and she called him Vinayaka. And she set him at the door, with a staff, and said, Let no one pass. And he said, No one shall pass; and he held the door.',
    'And Shiva came to the door, and the boy said, Thou shalt not pass; my mother is within, and has said that no one is to pass. And Shiva said, I am her husband. And the boy said, She said no one. And Shiva\'s attendants contended with the boy, and were turned back, and Shiva\'s anger rose, and the boy would not stand aside, for he had been told; and in the contest Shiva struck, and the head of the boy was severed.',
    'And Parvati came out, and saw; and her grief was without measure, and her anger was a thing that moved over the mountain; and she called up the forces of the world to destroy it, and the forces came, and were about to do it. And the gods cried to Shiva, and Shiva said, Go north, and take the head of the first creature you find who lies with its head to the north, and bring it.',
    'And the attendants went north, and the first they found was an elephant, a young one, lying with his head to the north; and they took his head, and brought it; and Shiva set it upon the shoulders of the boy, and sprinkled him with water, and breathed life into him, and the boy stood. And he had the head of an elephant, and the body of a boy, and his mother\'s love, and his father\'s name.',
    'And Shiva said, Thou shalt be the lord of the hosts, Ganapati; and thou shalt be honoured first, before all the gods, in every undertaking; and he who begins without thee shall not finish. And the people have honoured him first, at every door and every beginning, for the thousands of years since; and they say his name before the name of any other, and write it at the head of the page.',
    'And it is asked why the elephant. And the answer is the one the elders give: that the head was given by the first creature that was found, and that it was found lying toward the north, as it had been told; and that nobody in the whole matter was wrong, and that a child was made whole, and was loved, and is remembered by everyone who has ever begun a thing, whatever the thing, with a hope.'
  ] },
  { id: 'xiii', no: 'XIII', title: 'THE BOOK OF THE HARE', note: 'THE PEOPLES OF THE WAY: THE SASA JATAKA', verses: [
    'In a former life the one who was to be the Buddha was born a hare, and he lived in a wood, in a thicket at the foot of a hill, by a river, in the shade of a palm; and with him lived three friends: a monkey, a jackal, and an otter. And the four of them sat in the evenings and spoke of what was good.',
    'And the hare said to his friends, Know ye the day of observance? For it is a day to give; and to him that gives on that day, a great fruit shall come. Let us give, then, of what we have, to any who comes asking; and in the morning, if one comes, let us give it. And they agreed; and the four lay down in their places, and slept, and were light of heart.',
    'And in the early hour the otter went to the river, and found seven red fish that a fisherman had left on the sand, and he took them, and put them in a hollow. And the jackal found in a hut a lizard, and a pot of curds, and a skewer of meat, and brought them. And the monkey took mangoes from the tree, ripe, and set them by. And each said, I have something to give.',
    'But the hare thought, I eat only grass; and grass is not a thing to give a guest; and I have nothing else. And he thought for a long time, and he thought, If one comes to me, I will give my own body. And this was thought, in the wood, in the hour before the day, and heard by Sakka, who is the king of the gods, and whose throne grew hot with it.',
    'And Sakka took the form of a Brahmin, and came, and stood before the four, and said, I am hungry; I have come a long way. And the otter said, Here are seven fish; and the jackal, Here is meat and curd; and the monkey, Here are mangoes; and the Brahmin said, I will return after the three have laid them out, and I will see what the fourth has; and he turned to the hare.',
    'And the hare said, Brahmin, I have nothing but grass, and that is not a gift; but I will give myself. Light a fire, and when it is ready I will go into it, and thou shalt eat when it is cooked. And Sakka by his power made a fire, and it burned; and the hare, before he went, shook himself three times, lest there be a creature in his fur that should die in the flames, and then leapt, in perfect gladness, and the fire did not burn him, and was cool, as snow upon a leaf.',
    'And Sakka revealed himself, and said, Wise one, thy virtue shall be known to the end of this age; and he squeezed the mountain, and with the juice of it he drew upon the face of the moon the likeness of a hare. And it is there. And every night, whoever looks up, may see it, and the hare in the moon is not a story about a hare; it is the hare.'
  ] },
  { id: 'xiv', no: 'XIV', title: 'THE BOOK OF THE BRIDE', note: 'THE PEOPLES OF THE NORTH: THE LAY OF THRYM', verses: [
    'Wroth was Vingthor when he awoke, and his hammer he missed; his beard shook, his hair bristled; the son of Jord groped about him. And first of all these words he uttered: Hearken now to what I say, Loki; what no man knows on earth, nor in heaven above: the god\'s hammer is stolen.',
    'And they went to the fair court of Freyja, and Thor said, Wilt thou lend me thy feather-dress, that I may find my hammer? And Freyja said, I would give it thee were it of gold, and I would lend it thee were it of silver. And Loki flew, and the feather-dress whirred, until he came beyond the lands of the gods, and into the land of the giants.',
    'Thrym sat on a mound, the lord of the giants, plaiting gold collars for his hounds, and trimming the manes of his horses. And he said, How fares it with the gods? How fares it with the elves? Why art thou come alone to Jotunheim? And Loki said, Ill fares it with the gods and ill with the elves; hast thou hidden the hammer of Hlorrithi? And Thrym said, I have hidden the hammer eight leagues under the earth; no man shall get it again, unless he bring me Freyja to wife.',
    'And Loki flew back, and the feather-dress whirred, and he told Thor the word of Thrym. And they went to Freyja, and said, Bind on thee, Freyja, the bridal linen; we two shall drive to Jotunheim. And Freyja was wroth, and snorted with anger; all the halls of the gods trembled; the great necklace of the Brisings started from her. And she said, Most lustful of women should I be called if I drove with you to Jotunheim.',
    'Then Heimdall spoke, wisest of the gods, for he knew the future like the Vanir: Let us clothe Thor with the bridal linen; let him wear the great necklace of the Brisings. Let keys jingle by his side, and woman\'s dress fall about his knees, and on his breast let us lay jewels, and set a neat cap upon his head. And Thor said, The gods will call me womanish if I let myself be clothed in bridal linen. And Loki said, Be silent, Thor, such words are of no use; the giants will soon dwell in Asgard if thou dost not fetch thy hammer.',
    'So they clothed Thor in the bridal linen, and with the great necklace, and Loki went with him as the maid, and they drove the goats home, and the mountains burst and the earth burned with fire. And Thrym said, Stand up, giants, and strew the benches; they bring me Freyja, the daughter of Njord, to wife. And the bride sat down, and ate an ox, and eight salmon, and all the dainties that were meant for the women; and drank three casks of mead.',
    'And Thrym said, Who ever saw a bride bite more sharply? I never saw a bride eat more, nor a maid drink more mead. And the maid, who was Loki, sat by, and answered the giant\'s word: Freyja has eaten nothing for eight nights, so eager was she for Jotunheim. And Thrym lifted the veil, and desired to kiss her, but started back the length of the hall: Why are Freyja\'s eyes so terrible? Fire seems to burn from them. And the maid said, She has not slept for eight nights, so eager was she for Jotunheim.',
    'Then they brought the hammer in to hallow the bride; they laid Mjollnir in the maiden\'s lap; and then Thor laughed in his heart, who was hard of mood, when he felt the hammer in his hand. He slew Thrym the king of the giants, and crushed all the race of the giants. And so Thor got his hammer back. And this is the manner in which the god of thunder was a bride, and it is told as it was, and is not told otherwise.'
  ] }
];
