/* THE BIBEL, the first four chapters. Written the way scripture is written by people who believe it: gravely, exactly, in order, and with no sign that anything in it is strange.
   A verse is one string. Nothing here is a joke: it is all true, and the compilers have checked. */
export const PART_ONE = [
  { id: 'i', no: 'I', title: 'IN THE BEGINNING, AND AFTER', verses: [
    'In the beginning there was nothing, and the nothing was not empty, for it was full of the place where everything would go. And God moved upon the face of it, and the face was without form, and God gave it one.',
    'And God said, Let there be light: and there was light. And God saw the light, that it was good; and He divided the light from the darkness, and set a boundary between them, and the boundary stood exactly where He had said it should.',
    'And God divided the light from the darkness a second time, for the first division had been made in haste, and a thin grey had remained at the edge that belonged to neither. And God named the grey evening, and gave it to the dusk, and the dusk received it with thanks, and keeps it still.',
    'And on the second day God made the firmament, and hung it, and it was hung. And the waters above were parted from the waters beneath, that neither should presume upon the other; and God measured the distance between them, and it was found to be sufficient, and He wrote the figure down, and the figure is with Him.',
    'And on the third day God gathered the waters into one place, and the dry land appeared; and He called the waters seas, and they were many, and they were more than He had meant. And He looked upon the quantity of them, and did not undo it, and from that day the sea has been the sea.',
    'And on the fourth day God set the lights in the firmament, the greater to rule the day and the lesser to rule the night, and the stars also. And the days were reckoned, and one was found to be missing from the count; wherefore the fourth day was kept twice, once for work and once for rest, and this is why the calendars of the nations do not agree, and have never agreed, and will not.',
    'And upon the back of a great turtle the world was set, in the country of the Lenape and the country of the Hindus and wherever else the turtle is known; and the turtle bears it, and has borne it from before the first day, and has not been thanked. And she does not require it. But it is written here, that it may be on the record.',
    'In another country it is written that the world was an egg, and that Pangu slept within it for eighteen thousand years, and that when he woke he stood, and parted the sky from the earth with his back; and every day he grew a span, and the sky rose a span, and the earth sank a span, until they were far apart. And this also is true, for Pangu and the Lord are the same, who was one at the beginning and is many in the telling.',
    'And in the land between two rivers it is written that Marduk divided the body of Tiamat, and of the one half made the heavens, and of the other the earth; and that the rivers flow from her eyes. And the people of that country are not to be corrected, for they were there, and what they saw was the same thing that all the others saw, from a different place.',
    'And God saw everything that He had made, and, behold, it was very good; and it was not yet finished; and He did not say that it was finished, for it is not.'
  ] },
  { id: 'ii', no: 'II', title: 'THE MAKING OF PEOPLE', verses: [
    'And God took clay of the ground, and shaped it, and breathed into its nostrils the breath of life, and it sneezed; and God said, Bless thee, and the man was blessed, and that is the origin of the blessing.',
    'And God named the first man Adam, and the second man also Adam, and this is why there is such confusion in the records. For the first Adam was of the red earth, and the second was of the red earth also, and the scribes of the two houses wrote of them in the same words, and the compilers have kept both, and there are two.',
    'And God caused a deep sleep to fall upon Adam, and took one of his ribs, and closed up the flesh in its place; and of the rib He made a woman, and brought her to the man. And Adam said, This is now bone of my bones, and flesh of my flesh; and she was called Eve, because she was the mother of all living; and from her patience came everything that followed.',
    'In the land of the Hindus it is written that the first man was Purusha, who had a thousand heads and a thousand eyes and a thousand feet, and that the gods made an offering of him, and from his mouth came the priests, and from his arms the warriors, and from his thighs the merchants, and from his feet the people who work the land; and this is true as the account of a thing that was done once, in order that it should not need to be done again.',
    'In the land of the Maya it is written that the gods made men first of mud, and the mud crumbled; and of wood, and the wood forgot them; and at last of maize, white and yellow, ground by the grandmother and kneaded, and the maize people were the first who were able to give thanks. And the gods were satisfied, and the account of the mud and the wood was kept for the humility of men.',
    'In the country of the Norse it is written that the three sons of Borr found two trees upon the shore, an ash and an elm, and gave them breath and wit and warmth; and in the country of the sea-people it is written that men were churned out of foam; and in a certain valley of the south it is written that a woman sang them into being, and has since asked not to be named. And her wish is respected here.',
    'And the elders of the peoples were asked how it could be that there were so many makings, and they answered in the one voice that it was the same making; that God had made men in every place at the same hour; and that He had been in every place at that hour, which is no difficulty for Him. And all accounts are therefore correct. This is administratively demanding, and it is theologically settled.'
  ] },
  { id: 'iii', no: 'III', title: 'THE GARDEN, AND THE FRUIT, AND THE PAPERWORK', verses: [
    'And the Lord God planted a garden eastward in Eden; and there He put the man whom He had formed. And out of the ground made the Lord God to grow every tree that is pleasant to the sight, and good for food; and the tree of life also in the midst of the garden, and the tree of the knowledge of good and evil.',
    'And the Lord God took the man, and put him into the garden to dress it and to keep it. And He gave one commandment, and the commandment was one; and it is recorded that one commandment is one more than is wise to give to anyone, and that He gave it nonetheless, for it was needed, and the reason has not been withheld.',
    'Now the serpent was more subtil than any beast of the field which the Lord God had made. And he said unto the woman, Ye shall not surely die. And this was true, in the sense that the serpent intended it; and it was the most vexing kind of true, for it was the kind that is exactly accurate and entirely misleading, and the woman had no way to know the difference, there having been no one yet to explain it.',
    'And when the woman saw that the tree was good for food, and that it was pleasant to the eyes, and a tree to be desired to make one wise, she took of the fruit thereof, and did eat, and gave also unto her husband with her; and he did eat. And the eyes of them both were opened, and the first thing that wisdom told them was that they had no clothes.',
    'And they sewed fig leaves together, and made themselves aprons; and the aprons were of a poor quality, being of figs, and they were sufficient for the afternoon. And they heard the voice of the Lord God walking in the garden in the cool of the day, and Adam and his wife hid themselves from the presence of the Lord God amongst the trees of the garden; and the Lord God called, Where art thou?, and He knew where he was.',
    'And the Lord God drove out the man; and He placed at the east of the garden of Eden cherubims, and a flaming sword which turned every way, to keep the way of the tree of life. And they were sent east of Eden, where the rent is lower; and the angel stands at the gate with the sword, and has received no instruction as to what is to be done should they come back and apologise.',
    'And it is recorded in the Book of the Garden, by the hand of the keeper, that the gate is not locked; and that the sword turns every way, and does not turn toward the one who comes in humility; and that no one has yet tried this; and that the keeper waits.'
  ] },
  { id: 'iv', no: 'IV', title: 'THE FLOOD, THE ARK, AND THE COMPLAINTS', verses: [
    'And God saw that the wickedness of man was great in the earth, and that every imagination of the thoughts of his heart was only evil continually. And it repented the Lord that He had made man on the earth, and it grieved Him at His heart; and the wickedness was of the ordinary kind, which is the worst, being everywhere.',
    'But Noah found grace in the eyes of the Lord. And God said unto Noah, Make thee an ark of gopher wood; rooms shalt thou make in the ark, and shalt pitch it within and without with pitch. And this is the fashion which thou shalt make it of: the length of the ark shall be three hundred cubits, the breadth of it fifty cubits, and the height of it thirty cubits.',
    'And in the land between the rivers it is written that the god Ea warned Utnapishtim, who was earlier, and who built a vessel of six decks and nine rooms to each deck, and loaded it with gold and silver and the seed of every living thing; and in the land of the Hindus it is written that Manu, who was first, took a small fish from the water and kept it from the great fish, and was told to build a boat. And Manu has never made anything of it. The three accounts are one account.',
    'And of every living thing of all flesh, two of every sort were brought into the ark, to keep them alive with Noah; they shall be male and female. But the unicorns did not come, because they were arguing, and they were left behind, and are not found. And they are mourned, and it is the only thing in the whole record that is called a regret.',
    'And the rain was upon the earth forty days and forty nights, and the waters prevailed upon the earth an hundred and fifty days; and the ark went upon the face of the waters, and every living thing was destroyed which was upon the face of the ground. And the ark was provisioned; and the provisions were counted; and there was enough, which was a surprise to everyone but Noah.',
    'And Noah opened the window of the ark which he had made, and sent forth a raven, which went to and fro; and he sent forth a dove from him, and the dove found no rest for the sole of her foot, and returned. And again he sent forth the dove, and she came in to him in the evening; and, lo, in her mouth was an olive leaf pluckt off, and she had written upon the back of the leaf an account of the expenses of the journey.',
    'And God said, This is the token of the covenant which I make between Me and you and every living creature that is with you, for perpetual generations: I do set My bow in the cloud. And the covenant was this: that I will not do that again, in that particular way. And Noah said that he understood, and he understood.',
    'And the nations have asked, since, whether the covenant is in the whole of the matter; and the elders have replied that a promise is only as wide as its words, and that God is careful with His words, and that on the whole the nations have been grateful for the rainbow, and have not pressed the point.'
  ] }
];
