/* THE BIBEL, part two, the last five accounts, and part three: the one chapter on which every account agrees. Also the compilers' note, which is read first, and the colophon, which is read last. */
export const PART_TWO_B = [
  { id: 'xv', no: 'XV', title: 'THE BOOK OF THE HEAD', note: 'THE PEOPLES OF THE SEA: THE THEOGONY AND THE HYMNS', verses: [
    'In the beginning of the third age, Cronus, who had taken the throne of heaven from his father with a sickle of adamant, was told that a child of his own would take it from him. And he devoured his children as they were born: Hestia, and Demeter, and Hera, and Hades, and Poseidon; and he swallowed them whole, and they lived within him, and were not digested, for they were gods.',
    'And Rhea, his wife, being with child with Zeus, went to Crete, and bore him in a cave; and she wrapped a stone in swaddling clothes, and gave it to Cronus, and he swallowed the stone, and thought it a child. And Zeus was nursed by a goat, and fed by bees, and guarded by the Curetes, who beat their shields that the god should not hear the infant cry. And in due time he returned, and gave Cronus a drink, and Cronus brought up the stone, and his five children after it, whole, and grown.',
    'And Zeus, being king, took to wife Metis, whose name is counsel, who was the wisest of the gods and of mortal men. And Gaia and Ouranos said unto Zeus that Metis would bear a daughter of equal strength to himself, and after her a son who would be the lord of gods and men. And Zeus, forestalling this, deceived Metis with soft words, and swallowed her; and he was pregnant.',
    'And the days of the carrying were completed; and Zeus suffered a pain in his head so grievous that the heavens rang with it, and the sea answered with a great wave, and the gods looked upon him; and there was no remedy. And Zeus cried aloud, and sent for Hephaestus, who is the smith, and said, Take thy axe, and cleave my head.',
    'And Hephaestus took the double axe, and struck, and the head of Zeus was opened; and out of it leapt Athena, fully grown, in her armour of bronze, and her spear in her hand, with a war cry that shook the whole of Olympus, and the earth, and the waters. And the sun stopped in its course, for the wonder of it; and Helios stood his horses, until the goddess had put by her shield.',
    'And Zeus was relieved of the pain, and looked upon his daughter, and was glad; and he has never been known to repent of what he did to her mother, though Metis is said to be still within him, and to give him counsel, from his belly, in a small, wise voice; and it is the counsel that makes him the wisest of the gods, though it comes from the one he swallowed.',
    'And Athena was given the city that was named for her; and the olive; and the owl; and the weaving of wool; and the care of those who think; and she has never needed a mother, for she had a father who was a head. And the compilers have set the account down in the order in which the Greeks set it, and in the voice in which they told it, and it is not for the compilers to say that any part of it is out of order.'
  ] },
  { id: 'xvi', no: 'XVI', title: 'THE BOOK OF THE RED BEER', note: 'THE PEOPLE OF THE TWO LANDS: THE BOOK OF THE HEAVENLY COW', verses: [
    'It came to pass in the reign of Ra, when Ra was king of the gods and of men, that his majesty began to grow old; his bones were of silver, his flesh of gold, and his hair of lapis lazuli. And mankind, perceiving that the king was old, spoke against him in their hearts, and plotted, in the places where they were not heard; and Ra heard them.',
    'And Ra said to his followers, Summon to me my Eye, and Shu, and Tefnut, and Geb, and Nut, and the fathers and mothers who were with me when I was in the Waters; and the gods came, and bowed before him, and Ra said, Tell me what ye counsel concerning men, who have plotted against me; for I will not slay them until I have heard your word. And they said, Send forth thine Eye, that it may smite them.',
    'And the Eye of Ra went down, as the goddess Hathor, and smote mankind in the desert; and she was well pleased with the slaughter; and she became Sekhmet, the powerful one, the lady of the red linen; and she waded in their blood upon the mountains, and her heart was glad; and the nights were long, and she was not tired.',
    'And Ra said, I have the power to stop her, and I will; I would save the rest of them, for I am yet their king. And he spoke to his messengers: Run quickly, to Elephantine, and bring me red ochre, much of it. And the ochre was brought, and ground by the priestesses of Heliopolis; and the brewers brewed beer, seven thousand jars of it; and the red ochre was mixed in, and it was the colour of blood.',
    'And in the night, before the dawn of the day when the goddess was to come to the place, the beer was carried to the fields, and poured out, and it covered the fields of three palms in depth; and Ra said, It is good; thus will I save mankind. And at the dawn the goddess came, and looked upon the fields, and saw them flooded with what seemed to her blood; and her face was reflected there, and was beautiful, and she was pleased.',
    'And she stooped, and drank; and it was good, and she drank more; and her heart was glad within her, and she became drunk, and she did not perceive mankind. And she went back to Ra, and Ra said, Come in peace, O Hathor, for the lady is returned. And she was Hathor again, the lady of love, and of joy; and the slaughter was not completed, and men lived.',
    'And it was decreed that at every festival of the goddess, in the Year, jars of red beer should be brewed in the same number, and the priestesses should drink, and the whole of the land should drink with them, and should dance and sing; and it is so done; and it is the oldest feast on the earth; and it is the feast of a mercy that was brewed.'
  ] },
  { id: 'xvii', no: 'XVII', title: 'THE BOOK OF THE CAVE', note: 'THE PEOPLE OF THE ISLANDS OF THE SUN: THE KOJIKI', verses: [
    'Now Amaterasu, the goddess of the sun, who rules the Plain of High Heaven, sat in her sacred weaving hall, weaving the garments of the gods; and her brother Susanoo, the storm, who had been sent from the heavens for his rages and had returned to say farewell, was not content with leaving. And he broke down the ridges between her rice fields, and filled in her irrigation ditches, and fouled the hall in which she tasted the first fruits.',
    'And when the goddess did not rebuke him, but said that he must have been drunk, and meant well, he grew worse; and he flayed a piebald colt of heaven, backward, and cast it through a hole broken in the roof of the weaving hall, and a weaving maiden, seeing it, was so startled that she struck herself upon the shuttle, and died. And Amaterasu was afraid, and went into the Heavenly Rock Cave, and shut the door with a stone.',
    'And the Plain of High Heaven was dark, and the Central Land of Reed Plains was dark; and perpetual night came; and the voices of the myriad evil deities were as the buzzing of summer flies, and all calamities arose. And the eight hundred myriad gods assembled in the dry bed of the Heavenly River, and took counsel how to entice her out; and Omoikane, the god of thought, who thinks for many, had a plan.',
    'And they gathered the long-singing birds of eternal night, and made them sing; and they took the iron from the Heavenly Mountain and made a mirror; and of the curved jewels they made a necklace; and they uprooted a sacred tree and hung the mirror upon its middle branches and the jewels upon its upper; and they hung offerings of blue and white cloth from the lower; and the god of the offerings held them forth, and Ame-no-Koyane recited a prayer.',
    'And Ame-no-Uzume, the goddess of dawn and of laughter, turned a tub bottom up before the door of the Rock Cave, and stood upon it; and she stamped, and made a great noise; and she danced as one possessed, with clubmoss for a sash and a bundle of bamboo grass in her hand; and the eight hundred myriad gods laughed together, and the Plain of High Heaven shook with the sound.',
    'And Amaterasu in the cave was astonished, and she opened the door a very little, and said, Since I have hidden, the Plain of High Heaven must be dark, and the Reed Plains also; why then does Uzume dance, and why do the gods all laugh? And Uzume said, We rejoice and dance, because there is here a deity more illustrious than thou. And at this the mirror was held up, and the goddess looked, and saw a shining face, and thought it a stranger\'s, and came a step nearer to see it.',
    'And the god of the strong hand, who stood hidden beside the door, took her by the hand and drew her out; and another god stretched a rope of straw behind her, saying, Thou mayest not go back farther than this. And the Plain of High Heaven and the Reed Plains were light again, of themselves; and the sun rose, and rises; and the rope is still hung at the shrines of the country, as a promise that she may not go in again, and it is the oldest of the ropes.'
  ] },
  { id: 'xviii', no: 'XVIII', title: 'THE BOOK OF THE BUTTERFLY', note: 'THE PEOPLE OF THE WAY: THE BOOK OF CHUANG TZU', verses: [
    'Once Chuang Chou dreamed he was a butterfly, a butterfly flitting and fluttering about, happy with himself and doing as he pleased. He did not know that he was Chuang Chou. And he was happy, and there was nowhere he had to be; and the flowers were many, and he went to each of them in turn, and did not ask which was the better.',
    'Suddenly he woke up, and there he was, solid and unmistakable Chuang Chou. And he sat upon his bed, in his room, and he was the man who had woken, and was very much a man, with a name, and a back that ached, and a beard to be combed; and he did not know whether it was Chou who had dreamed he was a butterfly, or a butterfly who was dreaming he was Chou.',
    'And he considered the matter for a long time; and a disciple came and asked what he considered; and Chuang Chou told him; and the disciple said, Master, it is surely a plain question: thou art a man. And Chuang Chou said, And if the butterfly asks the same question, is he not right to say that he is a butterfly? And the disciple said nothing, and went away, and fetched tea.',
    'And Chuang Chou said that between Chou and the butterfly there must be some distinction; for there was the one, who was awake, and the other, who was not; and that this is called the transformation of things. And he said no more about it, for he was a man who knew when a thing had been said; and the disciple wrote it down, and it is as the disciple wrote it.',
    'And it is told that when his wife died, Chuang Chou sat with his legs spread out on the ground, beating on a tub and singing; and his friend Hui Tzu came to mourn, and said, Thou hast lived with her, and she brought up thy children, and grew old; not to weep is enough; but to beat a tub and sing, is that not too much? And Chuang Chou said, It is not so. When she first died, how could I not grieve? But I looked back to her beginning, before she was born, and she had not yet a form, nor a breath, nor a life.',
    'And between the confusion of nothingness something changed, and there was a breath; and the breath changed, and there was a form; and the form changed, and there was life; and now there is another change, and there is death. It is like the progress of the four seasons, spring, summer, autumn, winter. And she is lying peacefully in the great room; and for me to go about weeping would show that I did not understand fate; so I stopped.',
    'And in the evening the butterfly came to the window, in the lamplight, and was a butterfly, and went again, into the dark, and did not return; and Chuang Chou watched it go, and did not follow, and did not say that it was or was not himself; and went in to his supper, a man, with a beard, and slept; and it is not recorded what he dreamed.'
  ] },
  { id: 'xix', no: 'XIX', title: 'THE BOOK OF THE JAWBONE', note: 'THE PEOPLE OF THE GREAT OCEAN: THE TALES OF MAUI', verses: [
    'In the beginning the days of the world were short. The sun rose early and was soon gone again, and the people had no time to do their work. And the mother of Maui, whose name was Taranga, hung her cloth out to dry upon the stones in the morning, and before it had dried the night was come. And she wept, and it was seen by her youngest son, who was Maui, who was clever, and was not tall.',
    'And Maui said, Mother, I will see to it. And he went to his brothers, and said, We will catch the sun, and we will make him go slowly. And the brothers laughed, for the sun is a god, and a fire, and could not be caught; and Maui said, I have a plan. And they plaited ropes of flax, and they plaited them with the hair of Maui\'s sister Hina, whose hair was strong, and they twisted them tight with their hands, and the ropes were the thickest that had been made in the world.',
    'And they travelled many nights, by the dark of the earth, toward the place where the sun rises; and the way is long, and they lay up through the days, that the sun should not see them go; and they came to the east, to the great pit from which the sun climbs; and there they made a long wall of clay, and wove a net, and set the snares in a row, where the sun would put his head.',
    'And at the dawn, Tama-nui-te-ra the sun, climbed up out of the pit; and first came his head, and the loops caught him about the head, and the ropes drew taut; and he roared, and he beat the heavens with his light, and the ropes held; and the brothers hauled upon them, until their hands bled, and the sun was held in the snare, and could not rise, and the day stood still.',
    'And Maui stood out before the sun, and took in his hand the jawbone of his grandmother Muri-ranga-whenua, which he had carried with him all the way, the same jawbone with which he had once fished up the islands out of the sea; and he struck the sun with it; and struck him, many times, with all his might, until the sun was weak and cried out, Why dost thou treat me thus? Dost thou not know that I am a god?',
    'And Maui said, I know that thou art a god; and I will let thee go, if thou wilt promise to go more slowly across the sky. And the sun was in pain, and was lame, from the blows of the jawbone, and he gave his word; and the ropes were loosed; and from that day the sun has moved slowly, being lame, and the days are long enough for the drying of a cloth, and for the work of the people, and for their rest.',
    'And that is why the sun limps across the sky; and why, at the rising, the light is red, as with the marks of a blow; and why, in the long days of the summer, when he goes slowest, the people say, This is the sun that Maui beat, and was forgiven, and has kept his word. And it is not to be said that he does it unwillingly, for he was a god, and a promise is a promise.'
  ] }
];

export const PART_THREE = [
  { id: 'xx', no: 'XX', title: 'THE PART EVERYONE AGREES ON', verses: [
    'And in the end, past all of it, past the six days and the eight days, past the ark and the ladder and the wheel, past the argument about the calendar and the argument about the word for the one who keeps the book, every account says the same small thing, in its own alphabet, near the back, where no one looks.',
    'Be good to the stranger. For thou wast a stranger in the land of Egypt; and he who was a stranger is at thy door; and the door is thine to open, and it is the only door in the matter, and it is not locked.',
    'Feed whoever is hungry. Feed him before thou asketh his name, and before thou knowest his people; for hunger has no creed, and bread has none, and the one who is fed will tell thee his name, in his own time, with his mouth full.',
    'Do not be cruel because it is cheap. Cruelty is the cheapest of the things; it costs a moment, and is paid for by a lifetime, and not by the one who spends it; and the ledger, wherever it is kept, has an entry for it, and the entry is in the same hand as all the others.',
    'Forgive faster than is comfortable. It is not that the wrong was small; it was not; it is that the one who carries it carries it alone, and that the carrying is the heavier part; and the one who sets it down is lighter, and does not become a fool, but only lighter.',
    'That is the whole of it. The rest is commentary; and the commentary is nine hundred pages; and the commentary is where all the trouble comes from; and it is not to be thrown away, for it was written by people who loved the text, and who were trying to keep it from being forgotten; and it may be read, and it may be left; but it is not the text.',
    'Go now. Wash thy hands. Eat what is set before thee. Say a word to the one who is next to thee. It is later than thou thinkest, and it is earlier than thou fearest; and there is time, and there is bread, and there is the door; and thou art not alone in the house.'
  ] }
];

export const PREFACE = {
  id: 'p', no: '', title: 'THE COMPILERS\' NOTE', verses: [
    'This book is compiled from every book that claims to be the last one. It begins at the beginning, as the books do, and it goes where they go, in the order in which they go, and it does not hurry.',
    'Where the sources disagree, both are printed. Where the sources agree, the matter is settled. And where a source tells of a thing that cannot be, it is printed as it was told, for the one who told it was there, and the compilers were not, and have no cause to be surer than the one who was.',
    'The compilers have not added to it, nor taken from it, nor explained it. They have set the accounts side by side on the one table, and have read them in the one voice, and have found that they were, on the whole, saying the same thing in different rooms.',
    'It is a long book. It may be read from the beginning, or from the middle; it may be read in a night or in a year; and it is not required that it be read in order, though it is in order. A bookmark is provided. The reader is asked to be gentle with the margins.'
  ]
};
export const COLOPHON = {
  id: 'z', no: '', title: 'HERE ENDETH THE BIBEL', verses: [
    'Here endeth the Bibel. Amen, amen, om, selah, so be it.',
    'It was compiled and set in order by the compilers; and the compilers are not named; and they ask nothing, except that the next person to come to a door should open it.'
  ]
};
