/* CRAZY DAVE — what he says. Content only. */
export const DAVE_LINES = [
  'CRAAAZY DAVE! THAT\'S ME! THAT\'S WHAT THEY PUT ON THE FORM!',
  'I ATE A FRAME ONCE. TASTED LIKE A MONITOR. DIDN\'T LEARN A THING.',
  'YOU LOOK LIKE A MAN WHO NEEDS A SECOND POT AND A FIRST PLAN.',
  'THE POT ON MY HEAD IS NOT FOR SALE. THE POT ON MY HEAD IS LOAD-BEARING.',
  'I DON\'T DO REFUNDS. I DON\'T DO RECEIPTS. I DO GESTURES.',
  'THIS ONE\'S GOT PIXELS IN IT. THEY ALL HAVE. THAT\'S NOT A SELLING POINT.',
  'MY BROTHER SOLD A CURSOR TO A MAN WITH NO HANDS. GREAT SALESMAN. TERRIBLE MAN.',
  'BUY THE GOLD ONE. GO ON. I\'LL WAIT. I\'VE GOT NOTHING ELSE ON.',
  'A MAN CAME IN YESTERDAY AND ASKED FOR HELP. IN A SHOP! IMAGINE!',
  'I GREW THIS SHOP FROM A SEED. THAT\'S A LIE. I FOUND IT.',
  'SUNSHINE! CURRENCY! SAME WORD ROUND HERE. VERY CONFUSING AT BREAKFAST.',
  'IF YOU HOVER OVER A FRAME IT GOES ON THE MACHINE. FREE. I HATE THAT FEATURE.',
  'THE CRACKED ONE WAS LIKE THAT WHEN IT GOT HERE. I HAVE WITNESSES. THEY\'RE LYING.',
  'I ONCE SLEPT INSIDE A MONITOR. WARM. LOUD. WOULD NOT AGAIN.',
  'DO YOU EVER THINK ABOUT SOIL? I DO. CONSTANTLY. IT\'S A PROBLEM.',
  'EVERYTHING IN HERE IS AUTHENTIC. NOTHING IN HERE IS REAL. BOTH TRUE.',
  'THAT\'S NOT MOSS ON THE OVERGROWN ONE. IT IS MOSS. I WAS TESTING YOU.',
  'PRICES WENT UP. PRICES WENT DOWN. NET EFFECT: PRICES.',
  'I HAVE NEVER USED A COMPUTER. I SELL THE OUTSIDES. THAT\'S THE GOOD BIT.',
  'YOU\'VE GOT THE LOOK OF A MAN WHO ALPHABETISES HIS SEEDS.',
  'SOMEBODY BOUGHT THE BROOM. THE BEAR CAME IN ABOUT IT. WE TALKED.',
  'IF YOU DON\'T LIKE MY LINES THERE ARE TWENTY MORE. THAT\'S THE WHOLE BUSINESS MODEL.',
  'I ACCEPT SUN, SUNSHINE, AND VERY WARM COMPLIMENTS. MOSTLY SUN.',
  'THIS SHOP HAS NO DOOR. HOW DID YOU GET IN. HOW DID I.',
  'NIGHTPEA PAYS AFTER DARK. I PAY ATTENTION NEVER. WE ALL HAVE A SCHEDULE.',
  'A POINTER IS A HAND YOU DON\'T HAVE TO WASH.',
  'THEY SAY BUY LOW SELL HIGH. I BUY NOTHING AND SHOUT.',
  'ONE DAY I\'LL SELL YOU SOMETHING USEFUL AND WE\'LL BOTH BE DISAPPOINTED.',
  'WATCH THE LAMP ON THE CHIN WHEN YOU OPEN A WINDOW. THAT\'S POWER, THAT IS.',
  'I\'M NOT CRAZY. I\'M DAVE. THE OTHER WORD IS MARKETING.',
  'THE BACKDROPS ARE REAL PICTURES. YOU GET THE FILE. I DON\'T KNOW WHERE I GOT THE CHICKENS.',
  'AN ELEPHANT IN A HAT. THAT\'S A WHOLE BUSINESS. THAT\'S MY BUSINESS.',
  'I SOLD A MAN FIVE LAYERS. HE SAID THREE WOULD DO. HE CAME BACK FOR THE OTHER TWO. THEY ALWAYS DO.',
  'ABSINTHE IS SIXTY-EIGHT PER CENT. THE REST IS MOSTLY REGRET.',
  'EVERYBODY WANTS A BANJO. NOBODY WANTS TO HEAR ONE. BOTH TRUE.',
  'THE HOLUNDER CORDIAL IS JUST JUICE. I SELL IT FOR THE MEN WHO ARE BRAVE ENOUGH TO STOP.',
  'FREE RANGE MEANS FREE RANGE. HE MIGHT MOVE YOUR THINGS. HE MIGHT SIT ON THEM. YOU\'LL FIND OUT.',
  'THE BLUEPRINT FRAME IS THE ONLY ONE WITH A MEASUREMENT ON IT. NOBODY CHECKED THE MEASUREMENT.',
  'EVERY FIFTH POT I SELL, THE POT SAYS THANK YOU. NOBODY ELSE HEARS IT.'
];

export const DAVE_BROKE = [
  'NO. NOT WITH THAT. NOT WITH ANY OF THAT.',
  'COME BACK WHEN THE POTS HAVE DONE SOMETHING FOR YOU.',
  'I\'VE SEEN EMPTIER POCKETS. I\'VE SEEN THEM ON YOU. LAST WEEK.',
  'THAT\'S NOT ENOUGH SUN. THAT\'S BARELY WEATHER.',
  'GO DIG SOMETHING UP. NOT HERE. ELSEWHERE.',
  'PUT IT BACK. GENTLY. IT KNOWS.',
  'NO SUN, NO SHOP. THAT\'S THE SIGN. THERE ISN\'T A SIGN. IT\'S IMPLIED.',
  'I ADMIRE THE CONFIDENCE. I DO NOT ACCEPT IT AS PAYMENT.',
  'THAT\'S A GOOD ELEPHANT HAT. YOU DO NOT HAVE THE SUN FOR IT.',
  'THE GATHERER IS CHEAPER THAN YOU THINK. YOU STILL CAN\'T AFFORD IT.'
];

/* ---- the crazy ones -----------------------------------------------------------------------------------------------------
   One hover in ten (CRAZY_RATE), Dave says one of these INSTEAD of what the thing in front of you really is. The other nine
   say what they always said (`it.blurb`). Three kinds, all drawn from the same pool for the card you are over:
     DAVE_CRAZY        anything, anywhere
     DAVE_CRAZY_CAT    about the shelf (keys are COS_CATS ids, kernel/cos.js)
     DAVE_CRAZY_ITEM   a function of the card: (it, cat) => the line, so it can say the name and the price
   A line is at most SPEECH_MAX characters: three lines of the bubble at the shop's own size, which is as tall as it starts
   (the bubble grows with what it says, and a taller bubble pushes the shelves down while the pointer is on them).
   apps/shop/lines_check.js holds all of that to its numbers. */
/* a card that is a secret: Dave will not say what it is, or what it takes (the name on the card is ??? too). Never longer than SPEECH_MAX. */
export const DAVE_SECRET = [
  'THAT ONE\'S UNDER THE COUNTER. I\'M NOT ALLOWED TO TELL YOU WHAT IT IS. I\'M NOT ALLOWED TO TELL YOU WHY.',
  'SHH. IT\'S A SECRET. EVEN I FORGET IT\'S A SECRET, SOME DAYS, AND SAY IT OUT LOUD.',
  'I HAVE BEEN TOLD NOT TO DISCUSS THE QUESTION MARKS. BY WHO. I CAN\'T SAY.',
  'YOU\'LL KNOW WHEN YOU\'VE EARNED IT. THE CARD GOES FROM ??? TO A WORD. THAT\'S THE WHOLE TRICK.',
  'NOT FOR SALE. NOT FOR ASKING ABOUT. NOT EVEN FOR LOOKING AT, REALLY, BUT HERE WE ARE.'
];

export const CRAZY_RATE = 0.1;
export const SPEECH_MAX = 140;

export const DAVE_CRAZY = [
  'I WAS BORN IN A DRAWER. I WAS RAISED BY WHATEVER WAS IN THE DRAWER. IT WAS MOSTLY TAPE.',
  'THE FLOOR IS LAVA. THE CEILING IS ALSO LAVA. I LIVE IN THE MIDDLE, WITH THE PRICES.',
  'SOMETIMES AT NIGHT THE POTS MOVE THEMSELVES. I HAVE STOPPED ASKING THEM TO STOP.',
  'I SOLD A MAN HIS OWN HAT. HE DIDN\'T RECOGNISE IT. NEITHER DID THE HAT.',
  'WHAT IF THE SUN IS THE SAME SUN, ALL THE TIME? THINK ABOUT THAT. NOW BUY SOMETHING.',
  'I ONCE HAD A LONG TALK WITH A STAIRCASE. IT WENT UP. THEN IT WENT DOWN. WE PARTED.',
  'THE NUMBER SEVEN IS WATCHING YOU. I SAY SEVEN BECAUSE SIX IS BUSY.',
  'I\'M NOT SAYING THE SHOP IS HAUNTED. I\'M SAYING THE TILL SAYS THANK YOU AT THREE IN THE MORNING.',
  'A GOOSE CAME IN AND ASKED FOR THE MANAGER. I AM THE MANAGER. IT BIT ME. I GAVE IT A RAISE.',
  'MY MOTHER SAID I COULD BE ANYTHING. I SAID A SHOP. SHE SAID ANYTHING ELSE. I\'M A SHOP NOW.',
  'I HAVE FIVE SENSES AND ONE I MADE UP. IT TELLS ME WHEN THE BEAR IS NEAR. IT IS NEAR.',
  'DO NOT LOOK AT THE CEILING. THE CEILING HAS BEEN LOOKING AT YOU SINCE MONDAY.',
  'I TRIED TO RETURN A DAY ONCE. THEY SAID I\'D HAD IT TOO LONG. I HADN\'T EVEN OPENED IT.',
  'I AM FOURTEEN PER CENT GRAVY AND I WILL NOT BE TAKING QUESTIONS.',
  'SOMEONE LEFT A TACO IN THE VAULT IN 1997. IT HAS BECOME A KIND OF MAYOR.',
  'IF YOU HEAR A KNOCKING IN THE WALLS IT\'S ME. I\'M IN THE WALLS. IT\'S FINE. I PAID.',
  'THE PRICES ARE SET BY A COMMITTEE. THE COMMITTEE IS A PIGEON. THE PIGEON IS UNIONISED.',
  'I LEARNED EVERYTHING I KNOW FROM A RADIO THAT WASN\'T PLUGGED IN. VERY WISE RADIO.',
  'BEES! I JUST WANTED TO SAY BEES. I HAVE NOTHING FURTHER. THANK YOU FOR YOUR TIME.',
  'I\'VE GOT A BROTHER, A COUSIN, AND A SECOND COUSIN WHO IS ALSO MY BROTHER. DON\'T ASK.',
  'THE DOOR IS A LIE. THE DOOR HAS ALWAYS BEEN A LIE. THE WINDOW IS NOT A WINDOW EITHER.',
  'I OPENED THIS SHOP TO MEET PEOPLE. SO FAR: YOU, A BEAR, AND A MAN WHO WAS A COAT.',
  'ONCE I WON AN ARGUMENT WITH THE WIND. IT\'S BEEN TERRIBLE FOR TRADE EVER SINCE.',
  'I KEEP MY SAVINGS IN A SOCK. THE SOCK KEEPS ITS OWN COUNSEL. NOBODY KNOWS WHERE THE SOCK IS.',
  'ALL MY BEST IDEAS COME TO ME IN THE BATH. I DON\'T HAVE A BATH. THE IDEAS ARE VERY WET.',
  'THE PRICE TAGS ARE JUST A SUGGESTION. THE SUGGESTION IS HOLDING A KNIFE. KIDDING. PROBABLY.',
  'I CAN HEAR COLOURS. THIS ROOM IS SORT OF A HUM. SOMEBODY IN HERE IS ALSO A SEVENTH.',
  'WHEN I WAS YOUNG I WANTED TO BE A CLOUD. NOW I\'M A SHOP. MY MOTHER WAS RIGHT AND I HATE IT.',
  'I TRADED A WHOLE MOUNTAIN FOR A BUTTON ONCE. IT\'S A GOOD BUTTON. IT DOES NOTHING. PERFECT.',
  'THE MOON OWES ME MONEY. I\'VE WRITTEN TO IT. IT KEEPS SENDING BACK TIDES.',
  'THERE IS A TINY MAN IN THE TILL. I\'VE ASKED HIM TO LEAVE. HE SAYS HE\'S THE TILL.',
  'DON\'T TOUCH THE THING IN THE CORNER. I\'M NOT KIDDING. THERE ISN\'T ONE. YOU\'LL SEE.',
  'I WROTE A POEM ABOUT SOIL. IT WAS LONG. IT WAS MOSTLY THE WORD SOIL. MY BEST WORK.',
  'I LOOKED INTO THE MIRROR AND IT SAID "NEXT!" AND THE QUEUE WAS ME. A LONG QUEUE OF ME.',
  'MY ACCOUNTANT IS A LEMON. HE\'S VERY SOUR ABOUT THE BOOKS. THE BOOKS ARE FINE. THEY\'RE LEMONS.',
  'I HAVE MET EVERY ONE OF YOU BEFORE. IN A DREAM. YOU WERE HOLDING A SPOON. WHY THE SPOON.',
  'SOMETIMES I LIE DOWN ON THE FLOOR AND LET THE CUSTOMERS WALK OVER ME. IT\'S CALLED A SERVICE.',
  'THE SHOP SMELLS OF POTS AND OLD LIGHT. I TRIED TO SELL THE SMELL. THE SMELL REFUSED.',
  'IF I HAD A TAIL I WOULD WAG IT. I DON\'T. THE TAIL IS A RUMOUR I SPREAD MYSELF.',
  'WHO WANTS A FUN FACT? I DON\'T HAVE ONE. I JUST LIKE SAYING IT. FUN FACT! THERE.',
  'I KEEP HEARING A CLOCK. THERE ARE NO CLOCKS. IT\'S A VERY PUNCTUAL SILENCE.',
  'AN OWL ONCE TOLD ME EVERYTHING HAPPENS FOR A REASON. THEN IT FLEW INTO A WINDOW. THERE\'S NO WINDOW.',
  'I\'VE BEEN A GOOD DAVE. I\'VE BEEN A BAD DAVE. TODAY I\'M A DAVE-SHAPED OPPORTUNITY.',
  'THE ELEVATOR IN THIS SHOP GOES SIDEWAYS. THERE\'S NO ELEVATOR. IT STILL GOES SIDEWAYS.',
  'I HAD A DREAM ABOUT AN ENORMOUS CHEQUE. I WOKE UP AND I WAS THE ENORMOUS CHEQUE. IT WAS A LOT.',
  'EVERYONE SAYS "DAVE, YOU CAN\'T SELL AIR." I\'VE SOLD THREE AIRS AND A PRETTY GOOD DRAUGHT.',
  'MY LEFT SHOE KNOWS MY RIGHT SHOE\'S PIN NUMBER. THEY HAVE NEVER BEEN APART. IT\'S A LOVE STORY.',
  'WE DON\'T HAVE A LOST AND FOUND. WE HAVE A FOUND AND LOST. YOU FIND IT, THEN YOU LOSE IT.',
  'I TALK TO MYSELF A LOT. I\'M A GREAT LISTENER. I NEVER INTERRUPT. I NEVER LEAVE.',
  'THERE\'S A STAIN ON THE WALL THAT LOOKS LIKE A FAMOUS PERSON. NOBODY KNOWS WHO. IT\'S THEIRS TO KEEP.',
  'I\'M AFRAID OF EXACTLY ONE THING AND I\'M NOT TELLING YOU WHAT. IT\'S SQUARE. THAT\'S ALL I\'LL SAY.',
  'THE SHOP CLOSES WHEN I FALL ASLEEP. I\'VE NEVER FALLEN ASLEEP. THE SHOP HAS NEVER CLOSED. IT\'S A PLEDGE.',
  'A CROW GAVE ME A BUTTON. I GAVE IT A COIN. THAT WAS THE FIRST SALE AT THIS SHOP, AND THE LAST ONE I REMEMBER.',
  'I\'VE BEEN HAVING THE SAME TUESDAY FOR EIGHT MONTHS. THE SHOP DOES NOT MIND. THE POTS DO.',
  'EVERY SO OFTEN I SHOUT "FETCH" AND SOMETHING BRINGS ME A THING. I DON\'T KNOW WHAT IT IS. I DON\'T LOOK.',
  'MY HANDS ARE EXTREMELY CALM. IT\'S THE REST OF ME. THE REST OF ME IS A WEATHER FRONT.',
  'GOOD NEWS! THE WALL IS BACK. BAD NEWS! IT WAS NEVER GONE. IT\'S BEEN HERE THE WHOLE TIME. WATCHING.',
  'IF THE LIGHTS GO OUT, DO NOT PANIC. DO PANIC A BIT. THAT\'S WHAT THE LIGHTS ARE FOR.',
  'I WAS ASKED TO LEAVE A SWAMP ONCE. THE SWAMP WAS VERY POLITE ABOUT IT. I STILL HAVE THE LETTER.',
  'WHOEVER KEEPS LEAVING SOCKS IN THE SEEDS: I\'M NOT MAD. I\'M IMPRESSED. THEY\'RE GROWING.'
];

export const DAVE_CRAZY_CAT = {
  solitaire: [
    'I DON\'T SELL THESE. A TROPHY HANDS THEM OVER. I JUST KEEP THE SHELF CLEAN.',
    'A CARD BACK IS THE ONLY PART OF A CARD NOBODY IS MEANT TO LOOK AT. I LOOK AT IT.',
    'THE TABLE IS THE BIGGEST THING YOU OWN AND THE LEAST DECORATED. I FIX THAT. WHEN YOU WIN.',
    'WINNING IS FIFTY-TWO CARDS FALLING OFF A TABLE. I\'VE DONE IT WITHOUT THE WINNING.'
  ],
  frame: [
    'A FRAME IS A HOLE WITH OPINIONS. I SELL THE OPINIONS. THE HOLE COMES FREE.',
    'I TRIED ON A FRAME. IT FIT. THE MONITOR DIDN\'T LIKE IT. WE\'RE NOT SPEAKING.',
    'THE MACHINE GETS DRESSED IN THE MORNING TOO. YOU JUST DON\'T SEE IT. I SEE IT. I SEE IT ALL.'
  ],
  logo: [
    'A LOGO IS A TATTOO FOR A BOX. THE BOX IS NEVER CONSULTED.',
    'I DESIGNED A LOGO ONCE. A CIRCLE. A MAN SAID "THAT\'S A CIRCLE." I SAID "IT\'S A LOGO." WE FOUGHT.',
    'THE LOGO GOES IN THE CORNER. EVERYBODY LOOKS AT THE CORNER. THAT\'S WHERE THE MONEY SLEEPS.'
  ],
  cursor: [
    'A POINTER IS A SMALL ARROW THAT FOLLOWS YOU. I HAVE ONE. HE\'S CALLED GARY. HE\'S NOT HERE.',
    'I POINTED AT A POINTER AND IT POINTED BACK. WE HAVE NEVER BEEN CLOSER.',
    'THEY ALL POINT. THAT\'S THE WHOLE FEATURE. I\'M SO PROUD OF THEM.'
  ],
  scheme: [
    'EVERY COLOUR IS JUST LIGHT HAVING A BAD DAY. BUY ONE AND GIVE THE LIGHT A WEEKEND.',
    'I CAN SEE ALL THE COLOURS. AND SOME THAT AREN\'T HERE. THOSE ARE EXTRA.',
    'BLUE IS COLD. RED IS HOT. GREEN IS MOSTLY WORRIED. IT\'S IN THE MANUAL. THERE\'S NO MANUAL.'
  ],
  pot: [
    'A POT IS A HAT FOR DIRT. DIRT IS VERY SHY. THAT\'S WHY IT NEEDS THE HAT.',
    'I WEAR A POT. YOU COULD WEAR A POT. NOBODY WOULD STOP YOU. NOBODY\'S HERE.',
    'THIS ONE HAS A HOLE IN THE BOTTOM. FOR THE WATER. ALSO FOR THE SECRETS.'
  ],
  seed: [
    'A SEED IS A TREE THAT HASN\'T MADE UP ITS MIND. DON\'T RUSH IT. IT KNOWS.',
    'I PLANTED A SEED AND WAITED. NOTHING. THEN I REMEMBERED I\'D PLANTED IT IN A CHAIR.',
    'SEEDS HAVE FEELINGS. SMALL ONES. MOSTLY HOPE, AND SOME GRUDGES.'
  ],
  wall: [
    'A BACKDROP IS A PICTURE YOU STAND IN FRONT OF. THE PICTURE IS NOT IMPRESSED.',
    'YOU\'RE BUYING A WINDOW TO SOMEWHERE ELSE. THE SOMEWHERE ELSE DOESN\'T KNOW YET.',
    'THE PICTURES ARE FLAT. I CHECKED. I WALKED INTO ONE. TWICE.'
  ],
  crayon: [
    'DRAWING IS JUST STANDING STILL AND LETTING THE HAND DO THE WALKING.',
    'I DREW A DOG ONCE. IT BECAME A COUCH. THE COUCH LIVES WITH ME NOW.',
    'A BRUSH IS A CRAYON WITH AMBITION. A LAYER IS A CRAYON WITH A LAWYER.'
  ],
  garage: [
    'MUSIC IS JUST AIR WITH A SCHEDULE. I SELL THE SCHEDULE.',
    'I HAD A BAND ONCE. ME, A BUCKET, AND A MAN ON THE ROOF WHO KEPT SHOUTING ENCORE.',
    'ONE OF THESE INSTRUMENTS IS A SPOON IN A COAT. I WON\'T SAY WHICH. IT\'S WATCHING.'
  ],
  drink: [
    'A DRINK IS A SMALL BATH FOR YOUR INSIDES. I HAVE NO FURTHER NOTES.',
    'EVERY BOTTLE HAS A STORY. USUALLY IT\'S "I WAS HERE, AND THEN I WASN\'T."',
    'DRINK WATER. ALSO THIS. IN THAT ORDER. OR THE OTHER ORDER. I\'M NOT A DOCTOR.'
  ],
  elephant: [
    'AN ELEPHANT NEVER FORGETS. I FORGET EVERYTHING. WE BALANCE EACH OTHER OUT.',
    'THE ELEPHANT WANTS A HAT. I WANT A HAT. IT\'S THE FIRST THING WE\'VE AGREED ON.',
    'HE\'S VERY QUIET. TOO QUIET. IT\'S FINE. HE\'S PROBABLY JUST BEING AN ELEPHANT.'
  ]
};

export const DAVE_CRAZY_ITEM = [
  it => it.name + '? I NAMED THAT ONE MYSELF. IN MY SLEEP. WHILE ARGUING WITH A SPOON.',
  it => 'YOU\'RE LOOKING AT THE ' + it.name + '. IT\'S LOOKING AT YOU. NEITHER OF YOU HAS BLINKED.',
  it => 'THE ' + it.name + ' COSTS ' + (it.price === 0 ? 'NOTHING. I KNOW. I\'M AS UPSET AS YOU ARE.' : it.price + ' SUN. I CAN\'T COUNT THAT HIGH. I ASKED A BIRD.'),
  it => 'I ONCE SOLD A ' + it.name + ' TO A GHOST. HE PAID IN COLD SPOTS. I\'M STILL WARM FOR IT.',
  it => 'BUY THE ' + it.name + ' AND I TELL NOBODY. DON\'T AND I TELL EVERYBODY. THERE IS NOBODY. I\'LL TELL THE POTS.',
  it => 'I\'VE DREAMED OF THE ' + it.name + ' SEVEN TIMES. IN THREE OF THEM I WAS THE ' + it.name + '. HARD TO SAY.',
  it => 'WHO NAMED THE ' + it.name + '? ME. I NAME EVERYTHING. EVEN THE THINGS THAT AREN\'T THINGS.',
  it => 'DON\'T TELL ANYONE, BUT THE ' + it.name + ' IS MY FAVOURITE. THE OTHERS CAN HEAR ME. SORRY, OTHERS.',
  it => 'THE ' + it.name + ' CAME WITH A WARNING LABEL. I ATE THE LABEL. NOW I\'M THE WARNING.',
  it => 'I HELD THE ' + it.name + ' UP TO THE LIGHT AND THE LIGHT SAID "NO THANKS." RUDE LIGHT.',
  it => it.price === 0 ? 'THE ' + it.name + ' IS FREE. FREE! LIKE A BIRD. LIKE A BIRD WITH NO USE FOR YOU.'
                       : 'FOR ' + it.price + ' SUN YOU GET THE ' + it.name + ' AND A SOLEMN LOOK FROM ME. THE LOOK IS EXTRA.',
  it => 'IF THE ' + it.name + ' COULD TALK IT WOULD SAY "DAVE, PUT ME DOWN." SO I DON\'T LET IT TALK.'
];

/* what Dave might say about this card, all kinds together (a line that would be empty is left out) */
export function crazyPool(cat, it) {
  const out = DAVE_CRAZY.slice();
  (DAVE_CRAZY_CAT[cat] || []).forEach(l => out.push(l));
  if (it) DAVE_CRAZY_ITEM.forEach(f => { const l = f(it, cat); if (l) out.push(l); });
  return out;
}

/* Dave's answer to a pointer arriving on a card. One in ten, one of the crazy lines (never the one he said last); the rest,
   exactly what the card has always said. `rng` is injectable (0 <= r < 1) so the rate can be measured; the voice remembers
   what it last said for itself, so a shop window has one, and a second window has its own. */
export function makeHoverTalk(rng) {
  rng = rng || (() => Math.random());     /* looked up on each draw, so a page that replaces Math.random is heard */
  let last = null;
  return function talk(cat, it) {
    if (rng() >= CRAZY_RATE) return { text: it.blurb || it.name, crazy: false };
    const pool = crazyPool(cat, it).filter(l => l !== last);
    const text = pool[Math.floor(rng() * pool.length)];
    last = text;
    return { text, crazy: true };
  };
}
