/* CRAZY DAVE — what he says when there is a goose on his head (one shop in twenty, once the credits have given you one). Content only; apps/shop/lines_check.js holds it to the bubble. */
export const DAVE_GOOSE_LAND = [
  'THERE IS A GOOSE ON MY HEAD. IT CAME WITH THE POT. I DID NOT ASK. I DID NOT COMPLAIN.',
  'DON\'T LOOK NOW, BUT I HAVE A GOOSE. DON\'T LOOK AT THE GOOSE. IT KNOWS.',
  'A GOOSE LANDED ON ME. I\'M TAKING IT AS A SIGN. THE SIGN SAYS HONK.',
  'THE GOOSE IS NOT FOR SALE. THE GOOSE IS A LOAN. FROM WHOM, I\'M NOT SAYING.',
  'MIND THE GOOSE. IT SITS ON THE POT. THE POT SITS ON ME. I SIT ON NOTHING. IT\'S A SYSTEM.',
  'THE GOOSE PAYS RENT IN HONKS. I\'M OWED NINE. THE LANDLORD IS ME. I\'M DISGUSTED.',
  'A GOOSE! ON MY HEAD! IT HAPPENS ONE TIME IN TWENTY. I\'VE COUNTED. ON MY FINGERS. THE GOOSE HELPED.',
  'THE GOOSE HAS TAKEN OVER THE POT. THE POT HAS TAKEN OVER ME. I TAKE OVER NOTHING.'
];
export const DAVE_GOOSE_POKE = [
  'THAT WASN\'T ME. THAT WAS THE GOOSE. I\'M A QUIET MAN.',
  'DON\'T POKE THE GOOSE. DON\'T POKE ME. POKE THE SHOP. THE SHOP FEELS NOTHING.',
  'IT BIT ME ONCE. I BIT IT BACK. WE\'RE NOT SPEAKING. WE\'RE HONKING.',
  'IF THE GOOSE LEAVES THE POT FALLS. IF THE POT FALLS I FALL. SO: PLEASE, NOBODY BREATHE.',
  'THE GOOSE WANTS THE GOLD ONE. THE GOOSE ALWAYS WANTS THE GOLD ONE. THE GOOSE IS A SNOB.',
  'I TRIED TO SELL IT A FRAME. IT ATE THE FRAME. IT PAID IN FEATHERS. FEATHERS ARE NOT SUN.'
];
export const DAVE_GOOSE_HONK = [
  'THAT WAS THE GOOSE. I HAVE A NICER VOICE. I\'M TOLD. BY THE GOOSE.',
  'IT\'S TALKING AGAIN. I\'M NOT. I\'M LISTENING. THIS IS THE CLOSEST WE\'VE EVER BEEN.',
  'YES. YES, I KNOW. HE KNOWS I KNOW. WE KNOW EACH OTHER.',
  'QUACK. NO. THE OTHER ONE. HONK. I ALWAYS GET THEM BACKWARDS.',
  'THE GOOSE SAYS HELLO. THE GOOSE SAYS EVERYTHING IS FINE. THE GOOSE IS LYING.'
];
