/* The Studio Course, part one, chapters 4 to 6: the roll (draw, select, move, resize, erase, undo, snap, zoom, velocity, the ruler,
   the keys), editing like a producer (copy, paste, duplicate, transpose, quantize, humanize, velocity) and the desk (EQ, compressor,
   drive, room, echo, pan, the limiter). See course_tour_a.js for what a step is. */
import { notesOf, newNotes, maxDur, velChanged, shiftedBy } from './course_util.js';

const mel = C => C.track('p_mel'), melWas = C => C.was('p_mel');
const selMel = C => C.G.sel === C.song.tracks.findIndex(t => t.id === 'p_mel');
const wasTrack = (C, id) => C.was(id) || { notes: [], eq: [0, 0, 0] };
const eq = (t, i) => ((t && t.eq) || [0, 0, 0])[i] || 0;
const num = (t, k, d) => (t && t[k] != null ? t[k] : d);

export const CH_B = [
  { id: 'roll', title: 'THE ROLL', blurb: 'Draw, move, stretch, erase, zoom, and play the keys.', needsPractice: true, steps: [
    { id: 'pick', say: ['The big grid in the middle is the piano roll. Time runs left to right (the numbers on the ruler are bars), pitch runs bottom to top, like the keys of a piano down the left, and a note is a bar: its left end is when it starts, its length is how long it lasts.', 'Select the MELODY card and we will write on it.'],
      goals: [['Select the MELODY track.', selMel]], target: ['css:.g-tracks'] },
    { id: 'draw', say: ['The DRAW tool puts a note where you click. How long it is depends on SNAP and LEN (we will get to those); drag to the right as you click and it stretches as you go. Pressing 1, 2 and 3 on the keyboard picks DRAW, SELECT and ERASE.'],
      goals: [['Choose DRAW.', C => C.G.tool === 'draw'], ['Click in empty space in the roll three times to put three new notes down.', C => notesOf(mel(C)).length >= notesOf(melWas(C)).length + 3]], seq: true, target: ['btn:DRAW', 'zone:roll'], hint: 'Click an empty cell. Clicking a note you already have selects it instead, so nothing is ever deleted by accident.' },
    { id: 'move', say: ['Click a note and it is selected (it lights up) and the Garage plays it so you hear what it is. Drag a selected note and it moves, in time and in pitch. Shift adds notes to the selection; hold Ctrl as you start dragging and you move a copy; drag the right end of a note to make it longer or shorter.'],
      goals: [['Click one of the notes to select it.', C => C.G.items.size >= 1, { on: C => { C.mem.before = JSON.parse(JSON.stringify(notesOf(mel(C)))); } }], ['Drag it somewhere new.', C => { const n = notesOf(mel(C)); return n.length === C.mem.before.length && newNotes(C.mem.before, n) >= 1; }], ['Drag the right edge of a note so it is longer.', C => maxDur(mel(C)) > maxDur(melWas(C)) + 0.2]],
      seq: true, target: ['zone:roll'], hint: 'The cursor changes to a hand over a note, and to a double arrow over its right edge.' },
    { id: 'erase', say: ['ERASE sweeps notes away as you drag across them. The right mouse button erases in any tool, and DELETE removes whatever is selected.'],
      goals: [['Choose ERASE (or press 3).', C => C.G.tool === 'erase'], ['Sweep over a note, or right-click one, and it goes.', C => notesOf(mel(C)).length < notesOf(melWas(C)).length], ['Go back to the DRAW tool.', C => C.G.tool === 'draw']], seq: true, target: ['btn:ERASE', 'zone:roll'] },
    { id: 'undo', say: ['Everything you do can be taken back: eighty steps of it. UNDO and REDO are the two buttons after LEN (CTRL+Z and CTRL+Y). Nothing is permanent until you save, and even then you can open the song again and undo.'],
      goals: [['Press UNDO.', C => C.used('undo')], ['Press REDO.', C => C.used('redo')]], seq: true, target: ['btn:UNDO', 'btn:REDO'] },
    { id: 'snap', say: ['SNAP is the grid notes jump to as you draw and drag: 1/4 is every beat, 1/8 every half-beat, 1/16 every quarter-beat, and OFF lets you place a note anywhere. LEN is how long a new note is: SNAP means "as long as one grid step".', 'Careful drummers use 1/16; careful composers use 1/8.'],
      goals: [['Set SNAP to 1/8.', C => C.G.snap === 3], ['Set LEN to 1/4.', C => C.G.noteLen === 1], ['Draw a note: it is exactly one beat long.', C => notesOf(mel(C)).some(n => Math.abs(n[1] - 1) < 0.01 && newNotes(notesOf(melWas(C)), [n]) === 1)]], seq: true, target: ['css:.g-sel[title^="THE GRID"]', 'css:.g-sel[title^="HOW LONG"]'] },
    { id: 'zoom', say: ['− and + zoom the roll in time; ↕− and ↕+ change the height of the rows. Or hold Ctrl and use the wheel (Ctrl+Shift and the wheel for the rows). The strip across the top, above the roll, is the whole song in miniature: click it to jump about.'],
      goals: [['Press − to zoom out.', C => C.G.zoomX < C.startG.zoomX * 0.9], ['Press + to zoom in past where you started.', C => C.G.zoomX > C.startG.zoomX * 1.1], ['Press ↕+ to make the rows taller.', C => C.G.zoomY > C.startG.zoomY * 1.1]], seq: true, target: ['btn:−', 'btn:+', 'btn:↕+', 'css:.g-ov'] },
    { id: 'velocity', say: ['The strip under the roll is the velocity lane: one stick for every note, and its height is how hard the note is hit (harder is louder and brighter). Drag a stick up or down to change that note; drag across several sticks and the Garage draws a line through them.'],
      goals: [['Drag a stick in the velocity lane to a new height.', C => velChanged(notesOf(melWas(C)), notesOf(mel(C)))]], target: ['zone:vel'], hint: 'The lane is the strip along the bottom of the roll.' },
    { id: 'ruler', say: ['The ruler along the top is for time. Click it and the yellow cursor jumps there: PLAY and PASTE both start from it. Drag along it and you pick a stretch of the song, across every track (we will use that in a later chapter).'],
      goals: [['Click the ruler at bar 3: the yellow cursor moves.', C => C.G.cursor > 7 && C.G.cursor < 9], ['Press ⏮ (or HOME) to go back to the start.', C => C.G.cursor === 0]], seq: true, target: ['zone:ruler'] },
    { id: 'keys', say: ['Below the roll is the keyboard (the KEYBOARD tab; the MIXER tab is next to it). On the computer, A S D F G H J K L are the white keys and W E T Y U O P the black ones; Z and X move the octave. Click a key in the dock and it plays too.', 'REC turns the keyboard into a recorder: press REC, play, and what you play is written into the selected track, snapped to the grid.'],
      goals: [['Play a few notes on the keys: press A, S, D, F on your keyboard.', C => ['a', 's', 'd', 'f'].every(k => C.keys.indexOf(k) >= 0)], ['Press REC, play four notes and press STOP: they appear in the track.', C => C.used('record') && notesOf(mel(C)).length >= notesOf(melWas(C)).length + 3]],
      seq: true, target: ['css:.g-keyhost', 'btn:REC'], hint: 'REC needs the song to be playing: pressing it starts playback for you.' }
  ] },

  { id: 'edit', title: 'EDIT LIKE A PRODUCER', blurb: 'Copy, paste, transpose, quantize, humanize, soften.', needsPractice: true, fresh: true, steps: [
    { id: 'copy', say: ['The edit bar has the tools every producer lives in. ALL selects every note of the track; COPY, CUT and PASTE move them about; DUP copies the selection straight after itself; DEL deletes. PASTE puts things where the yellow cursor is, so click the ruler first.'],
      goals: [['Select the MELODY track and press ALL (or CTRL+A): every note is selected.', C => selMel(C) && C.G.items.size === notesOf(mel(C)).length], ['Press COPY.', C => C.used('copy')], ['Click the ruler at bar 9 (or anywhere late) and press PASTE: the copy is put down there.', C => C.used('paste') && notesOf(mel(C)).length > notesOf(melWas(C)).length]], seq: true, target: ['btn:ALL', 'btn:COPY', 'btn:PASTE'], hint: 'Pasting past the end makes the song longer by itself.' },
    { id: 'dup', say: ['DUP is copy-and-paste in one press: the selection is copied straight after its own end. It is the fastest way to turn one bar into four.'],
      goals: [['Select a few notes and press DUP.', C => C.used('duplicate')], ['Press DEL to delete the copy.', C => C.used('del')]], seq: true, target: ['btn:DUP', 'btn:DEL'] },
    { id: 'transpose', fresh: true, say: ['Here is a real job. The practice song\'s MELODY sits an octave too low, buried under the strings. Fix it: select the MELODY track, select every note (ALL), then open MORE and choose TRANSPOSE UP AN OCTAVE (or press Shift+↑).', 'Transpose changes the notes themselves, not just the key, and keeps them in the same places in time.'],
      goals: [['Every melody note is one octave higher than it was, and none were added or lost.', C => shiftedBy(notesOf(wasTrack(C, 'p_mel')), notesOf(mel(C)), 12)]], target: ['btn:ALL', 'btn:MORE'], hint: 'MORE ▼ is the button next to QUANTIZE. Its menu also has HUMANIZE, LEGATO, HARDER, SOFTER and LONGER.' },
    { id: 'quantize', say: ['Quantize snaps notes to the grid so they are exactly on time, and it works on the selection, a picked stretch, or the whole track. HUMANIZE does the opposite: it loosens everything a little in time and touch so it sounds played rather than programmed.', 'SNAP says how strict QUANTIZE is: it needs a grid, so it will not work with SNAP on OFF.'],
      goals: [['MORE, then HUMANIZE.', C => C.used('humanize')], ['QUANTIZE, then FULL: they are back on the grid.', C => C.used('quantize')]], seq: true, target: ['btn:MORE', 'btn:QUANTIZE'] },
    { id: 'shape', say: ['The rest of the MORE menu shapes the notes: HARDER and SOFTER change how hard they are hit, the velocity RAMPS fade a selection in or out, LEGATO makes each note reach the next, LONGER and SHORTER (the [ and ] keys) change lengths by one grid step, and TRANSPOSE moves them by a semitone or an octave.'],
      goals: [['Select the CHORDS track, press ALL, then MORE and SOFTER.', C => C.calls('velocity').some(a => a[0] < 1)], ['MORE and LEGATO.', C => C.used('legato')], ['Select some notes and press ] to make them longer.', C => C.used('stretch')]], seq: true, target: ['btn:MORE'] }
  ] },

  { id: 'desk', title: 'THE DESK', blurb: 'EQ, compressor, drive, room, echo, pan and the limiter.', needsPractice: true, fresh: true, steps: [
    { id: 'open', say: ['Press the MIXER tab (or TAB) under the roll: a strip for every track, and one for the master. Press PLAY and watch the meters bounce: green is healthy, yellow is loud, red is clipping.'],
      goals: [['Open the MIXER.', C => C.G.dock === 'mixer'], ['Press PLAY and watch the meters for three seconds.', C => { if (C.api.player() && C.G.dock === 'mixer') { C.mem.t = C.mem.t || Date.now(); return Date.now() - C.mem.t > 3000; } C.mem.t = 0; return false; }]], seq: true, target: ['btn:MIXER', 'css:.g-mixer'] },
    { id: 'eq', say: ['EQ turns whole ranges of the sound up and down: LO is the boom, MID the body, HI the sparkle. The classic move is to cut the lows of everything that is not the bass, so the bass has the bottom of the song to itself. Here the strings are muddying the bass.'],
      goals: [['Cut LO on the CHORDS to -6 dB or lower.', C => eq(C.track('p_chd'), 0) <= -6], ['Boost HI on the MELODY by +4 dB or more.', C => eq(C.track('p_mel'), 2) >= 4]], seq: true, target: ['css:.g-strip.sel'], hint: 'Drag the small LO, MID and HI sliders. Double-click one to put it back.' },
    { id: 'comp', say: ['COMP is a compressor: it squashes the loud parts down so a note that is too loud and one that is too quiet end up the same size. It is why a good bass line sits firmly instead of jumping. DRIVE adds warmth and edge, the sound of a pushed valve: a little makes things fatter, a lot makes them fierce.'],
      goals: [['COMP on the BASS to 40 or more.', C => num(C.track('p_bas'), 'comp', 0) >= 0.4], ['DRIVE on the MELODY to 25 or more.', C => num(C.track('p_mel'), 'drive', 0) >= 0.25]], seq: true, target: ['css:.g-strip'] },
    { id: 'space', say: ['ROOM and ECHO are the two sends: they put the sound in a space. ROOM is the sound of a hall, soft and everywhere; ECHO repeats in time with the tempo, so it ticks along with the song. A dry sound is close and intimate; a wet one is far away and grand.', 'PAN places a track between the speakers. Keep the bass and the kick in the middle and spread the rest.'],
      goals: [['ROOM on the CHORDS to 40 or more.', C => num(C.track('p_chd'), 'reverb', 0.15) >= 0.4], ['ECHO on the MELODY to 25 or more.', C => num(C.track('p_mel'), 'echo', 0) >= 0.25], ['Pan the CHORDS 30% to one side.', C => Math.abs(num(C.track('p_chd'), 'pan', 0)) >= 0.3]], seq: true, target: ['css:.g-strip'] },
    { id: 'master', say: ['The last strip is the MASTER: everything added together. Its LIMITER is a wall: nothing can get louder than the number you choose, so a big chorus can never clip. -9 is gentle, -1 is as loud as it gets. MONO folds both speakers into one: if anything disappears when you press it, it was fighting its own echo.', 'PEAK is the loudest the music has been, RMS how loud it feels on average, and the spectrum shows how much of each pitch is sounding.'],
      goals: [['Set the LIMITER to -6 dB.', C => C.song.limit === -6], ['Press MONO to hear it in one speaker, then again to go back.', C => C.pressed('MONO') >= 2]], seq: true, target: ['css:.g-master'] },
    { id: 'read', manual: true, say: ['That is the whole desk. A good mix is not a recipe: it is listening, moving one slider, listening again. The two habits that help most are to turn things down instead of up (leave room before the limiter) and to listen in MONO from time to time.'], target: ['css:.g-spechost'] }
  ] }
];
